version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - sqlite-data:/app/data
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

volumes:
  sqlite-data:
